### PR TITLE
Cobra integration

### PR DESCRIPTION
**Pull request by rjmateus**
Integration with cobra framework to be used with sub-commands

Implements: https://github.com/SUSE/spacewalk/issues/14636

### CODE REVIEW

**Comment by rjmateus** [comment]
ping @admd @aaannz @MMuschner for awareness 
I plan to merge as soon  I can make one more full export/import test

**Comment by aaannz** [comment]
I am not really familiar with go projects organization, but wouldn't it be easier to maintain instead of adding copy of cobra project using git submodule pointing to the right git repo and version hash?

**Comment by rjmateus** [comment]
> I am not really familiar with go projects organization, but wouldn't it be easier to maintain instead of adding copy of cobra project using git submodule pointing to the right git repo and version hash?

I'm assuming you are talking about the vendor folder. I think is something to investigate.
That folder is managed by go and is needed to build the project on IBS. I don't know if we can use git submodule in IBS

**Comment by admd** [comment]
There are different approaches to handle dependencies when packaging go, one possible approach was discussed in the past was this one http://mailman.suse.de/mlarch/SuSE/galaxy-devel/2020/galaxy-devel.2020.09/msg00013.html . Which is really nice and clean.

**Comment by aaannz** [comment]
> There are different approaches to handle dependencies when packaging go, one possible approach was discussed in the past was this one http://mailman.suse.de/mlarch/SuSE/galaxy-devel/2020/galaxy-devel.2020.09/msg00013.html . Which is really nice and clean.

I like this. That would instantly make this PR 12k lines smaller :)

**Comment by admd** [comment]
If we decide to go that route, we can probably do that in a separate PR because we have some other package to remove as well.

**Comment by rjmateus** [comment]
Hey Abid. Great to hear that :)
I will made a PR to clean the vendor dependencies and merge before this one. 
The approach you sent will make it much cleaner

**Comment by rjmateus** [comment]
@aaannz @admd vendor folder remove. PR is much better now :nerd_face:

**Pull request merged**
